-- 출처: 프로그래머스 코딩 테스트 연습, https://programmers.co.kr/learn/challenges

-- 코딩테스트 연습 > SQL > JOIN
-- 없어진 기록 찾기
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I ON O.ANIMAL_ID=I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID;

-- 있었는데요 없었습니다
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O, ANIMAL_INS I
WHERE O.ANIMAL_ID = I.ANIMAL_ID
AND O.DATETIME<I.DATETIME
ORDER BY I.DATETIME;

-- 오랜 기간 보호한 동물(1)
SELECT I.NAME, I.DATETIME
FROM ANIMAL_INS I
LEFT JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE O.DATETIME IS NULL
ORDER BY I.DATETIME
LIMIT 3;

-- 보호소에서 중성화한 동물
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_OUTS O, ANIMAL_INS I
WHERE O.ANIMAL_ID=I.ANIMAL_ID
AND O.SEX_UPON_OUTCOME != I.SEX_UPON_INTAKE
ORDER BY O.ANIMAL_ID;
-- 중성화는 전후 관계가 바뀔 수 없기 때문에 조건을 설정할 때 두 값이 다른 데이터를 찾으면 된다.

-- 코딩테스트 연습 > SQL > STRING, DATE
-- 오랜 기간 보호한 동물(2)
SELECT O.ANIMAL_ID, O.NAME
FROM ANIMAL_OUTS O, ANIMAL_INS I
WHERE O.ANIMAL_ID=I.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;
-- 기간 : 날짜형 간의 뺄셈 DATEDIFF()